### ISSUE TITLE
What is the required input format for body surface?

### ISSUE THREAD

**Issue by siddhshenoy** [MarilynKeller/OSSO#10]
Hello,

I am trying to infer a skeleton using OSSO and have tried it on existing ply files provided in the demo/data folder. I was successful in generating the skeletons for them however, when I try to generate a skeleton for a PLY file which I created using the blender SMPL addon it gives me the following error:

Input mesh should have the same topology as STAR or SMPL.

I printed the total number of vertices that the input model has and what the STAR model expects, it gave me the following values:
**Input Mesh**: 7571 vertices
**STAR Mesh**: 6890 vertices

I searched if anyone has encountered this issue in the past (from the issues section) there seems to be one however it seems like they haven't provided a resolution over there.

Does the program expect a STAR specific model as an input?

**Comment by MarilynKeller** [comment]
Hello,

I am surprised you get a mesh that is 7571 vertices out of the SMPL blender add-on. The exported SMPL mesh should have 6890 vertices. Maybe you exported another object along ?
Can you share the .ply file?

**Comment by siddhshenoy** [comment]
Definitely, I am attaching the two screenshots along with the mesh attachment here.

The image below is the SMPL model created using the blender add-on (directly clicking the button for 'Add Model'):
**Note**: Here it shows a vertex count of 6890.

![image](https://github.com/MarilynKeller/OSSO/assets/10564285/847bff1c-432d-4f55-b99c-7c089d937b70)

**The image below is the SMPL model being reimported as a PLY file after being exported from the model created using the addon**

![image](https://github.com/MarilynKeller/OSSO/assets/10564285/f6929668-0e4d-4681-b8ab-2a704041eac1)

It happened to have more vertex count after I exported the SMPL model from blender. 

Additionally, I am attaching the blender export options for the PLY file:

![image](https://github.com/MarilynKeller/OSSO/assets/10564285/ea532d4c-509c-4719-88ef-0643ee5f13b6)

And here is the PLY file I exported from blender:

[test.zip](https://github.com/MarilynKeller/OSSO/files/11754664/test.zip)

**Comment by MarilynKeller** [comment]
Thanks for the detailed info. The mesh looks fine, I assume it is an export issue.
Can you try exporting the mesh with "selection only" checked?
If the number of vertices is still not 6890, try unchecking the 4 boxes in the geometry export options.

**Comment by siddhshenoy** [comment]
Yes, that resolved the vertex count issue. I investigated it a bit further as to which option was causing the issue, it seems like it was the "UVs" that caused the issue for me. Unchecking all the 4 checkboxes works too.

Thank you for your timely assistance, I'll close the issue.
