### ISSUE TITLE
About joints in skeleton model...

### ISSUE THREAD

**Issue by hwy1992129** [MarilynKeller/OSSO#11]
The paper mentions landmarks and joints. It seems that the skeleton doesn't have a tree structure or joints don't control the rotation of the bone...? Changing sp.t and sp.r_abs is change the translation and rotation in local space. The rotation center is the mean of the vertices' locations
What is the purpose of joints? Align the joints of the skeleton to the joints of the star model using cost calculation?

**Comment by MarilynKeller** [comment]
Indeed the skeleton does not have a kinematic tree but a translation and a rotation per bone group.
In the paper, we defined landmarks corresponding to the STAR joints to help the DXA fitting. But we don't have skeleton joints locations for say.
