### ISSUE TITLE
How to transform my mesh data into the network topology structure required by OSSO, where Vertices=6890?

### ISSUE THREAD

**Issue by YH188** [MarilynKeller/OSSO#13]
Dear Marilyn Keller,

I would like to obtain the internal skeletal structure of my surface data. My mesh data has Vertices=10127706, which does not meet the required vertex count for STAR. How can I modify it? Could you please guide me?

Kind regards,
Huan Yin

**Comment by MarilynKeller** [comment]
Dear Huan, Thanks for using Osso. Fist you need to align the SMPL model to your mesh. We do not release this code but you can look over there:https://github.com/bharat-b7/RVH_Mesh_RegistrationOr use meshcapade service but it's not free:https://me.meshcapade.com/from-scansThat will give you a SMPL mesh that has the same shape and pose as your mesh but has the topology requested to run the OSSO inference and get the skeleton.I hope this helps.Best, Marilyn KellerLe 22 nov. 2023 05:32, YH188 ***@***.***> a écrit :
Dear Marilyn Keller,
I would like to obtain the internal skeletal structure of my surface data. My mesh data has Vertices=10127706, which does not meet the required vertex count for STAR. How can I modify it? Could you please guide me?
Kind regards,
Huan Yin

**Comment by MarilynKeller** [comment]
To add more details for anyone stuck by this. To align SMPL to a scan, you can use the [smplx](https://github.com/vchoutas/smplx) package and pytorch. Use pytorch to optimize SMPL's shape (beta) and pose (theta) to minimize the distance between the SMPL mesh and your scan's mesh.

**Comment by MarilynKeller** [comment]
You can also try this service: https://me.meshcapade.com/from-scans
