### ISSUE TITLE
Where to get more demo body？

### ISSUE THREAD

**Issue by qaz8788817** [MarilynKeller/OSSO#14]
Hi, this is a truly impressive piece of work. I'd like to try out more models. Could you please let me know where I can find similar human body models for experimentation, like those in the demo folder?

Thank you.

**Comment by MarilynKeller** [comment]
Hi, you can find a large variety of SMPL bodies and sequences in the [AMASS Dataset](https://amass.is.tue.mpg.de/index.html)

In the download section, click on SMPL+H G
<img width="1058" alt="image" src="https://github.com/MarilynKeller/OSSO/assets/102662583/51fa2940-ffae-4815-9dd2-001aa2791915">

To vizualize those sequences of bodies in motion, you can use [AitViewer]( https://github.com/eth-ait/aitviewer).

Please also note that OSSO is a project from 2022, we now have a new body+skeleton model called SKEL that supports more applications: https://skel.is.tue.mpg.de/.

**Comment by qaz8788817** [comment]
> Hi, you can find a large variety of SMPL bodies and sequences in the [AMASS Dataset](https://amass.is.tue.mpg.de/index.html)
> 
> In the download section, click on SMPL+H G <img alt="image" width="1058" src="https://private-user-images.githubusercontent.com/102662583/307762349-51fa2940-ffae-4815-9dd2-001aa2791915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDI4MDksIm5iZiI6MTcwOTAwMjUwOSwicGF0aCI6Ii8xMDI2NjI1ODMvMzA3NzYyMzQ5LTUxZmEyOTQwLWZmYWUtNDgxNS05ZGQyLTAwMWFhMjc5MTkxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMjU1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjk2ZGZkNmIzZGFmNTliM2EwYjQ4YmZjOGZlODhhYWRmYjE2ZGIwMWI3YTZhZGQyOGIzYzk2N2EyNGNiNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6yuVq5iMfBTz4aYkUCy7LLGuEtqLEdefuye-jlGdHe0">
> 
> To vizualize those sequences of bodies in motion, you can use [AitViewer](https://github.com/eth-ait/aitviewer).
> 
> Please also note that OSSO is a project from 2022, we now have a new body+skeleton model called SKEL that supports more applications: https://skel.is.tue.mpg.de/.

Hi, thanks for your reply.
After I downloaded and decompressed one of the AMASS dataset, I got multiple sets of npz files. Should I use osso/utils/fit_osso.py to convert these files into ply files? Or there is a mistake in my understanding. 

Thank you.

**Comment by qaz8788817** [comment]
I'm not sure if it's appropriate to ask this question, and I apologize if it causes any inconvenience. I followed the instruction to download the CMU dataset from AMASS, and after extracting it, I obtained npz files containing different actions from various subjects. I used numpy to read one of the files, and the contents are as follows:
![image](https://github.com/MarilynKeller/OSSO/assets/73918947/8e47da9e-e575-4679-9ea0-b1a8e0ea00bb)
Here is no `vertices` and `faces` in these files.
I would like to convert these files into ply or obj format so that I can use main.py to generate skeletons. Is there any method to convert these npz files into obj or ply files?
Thank you.

**Comment by MarilynKeller** [comment]
The AMASS files contain sequences of parameters defining for each frame the pose (poses), body shape (betas) and translation (trans) of a human body.
To generate a 3D mesh out of them, you need to use SMPL. You can use it through the smplx library (https://github.com/vchoutas/smplx).

In your more recent project SKEL, we have a demo where we directly fit the SKEL skeleton model to an AMASS sequence. You can see an example of how we get the SMPL mesh vertices from the .npz dictionary [here](https://github.com/MarilynKeller/SKEL/blob/2534693ebfff8964e12de478be018e2a4f704b15/skel/alignment/aligner.py#L235)

**Comment by qaz8788817** [comment]
> The AMASS files contain sequences of parameters defining for each frame the pose (poses), body shape (betas) and translation (trans) of a human body. To generate a 3D mesh out of them, you need to use SMPL. You can use it through the smplx library (https://github.com/vchoutas/smplx).
> 
> You can see an example of how we get the SMPL mesh vertices from the .npz dictionary [here](https://github.com/MarilynKeller/SKEL/blob/2534693ebfff8964e12de478be018e2a4f704b15/skel/alignment/aligner.py#L235)
> 
> Note that In your more recent project [SKEL](https://github.com/MarilynKeller/SKEL), we have a demo where we directly fit the SKEL skeleton model to an AMASS sequence.

Thanks. I follow the SKEL installation steps to install aitviewer, and I cannot install it successfully. I have commented my error and question here: https://github.com/MarilynKeller/aitviewer-skel/issues/2#issuecomment-1972391757

Thanks.
