### ISSUE TITLE
Do you have a Colab notebook 

### ISSUE THREAD

**Issue by langzizhixin** [MarilynKeller/OSSO#4]
Do you have a Colab notebook for this project? It can run directly.

**Comment by MarilynKeller** [comment]
No we don't plan to release a colab notebook for this project.

**Comment by langzizhixin** [comment]
I wrote a Colab notebook  myself and ran it successfully.

**Comment by MarilynKeller** [comment]
Hi [langzizhixin](https://github.com/langzizhixin), are you willing to share your Colab Notebook? That would be a great contribution for the community.

**Comment by qaz8788817** [comment]
Hi @langzizhixin , can you share your Colab Notebook?
Thanks.
